(source gnu)
(source melpa)

(depends-on "cask")
(depends-on "company")
(depends-on "dash")
(depends-on "epl")
(depends-on "f")
(depends-on "flx")
(depends-on "flx-ido")
(depends-on "flycheck")
(depends-on "git-commit-mode")
(depends-on "git-rebase-mode")
(depends-on "idle-highlight-mode")
(depends-on "ido-ubiquitous")
(depends-on "ido-vertical-mode")
(depends-on "inf-ruby")
(depends-on "js2-mode")
(depends-on "key-chord")
(depends-on "let-alist")
(depends-on "magit")
(depends-on "package-build")
(depends-on "pallet")
(depends-on "perspective")
(depends-on "pkg-info")
(depends-on "popwin")
(depends-on "s")
(depends-on "shut-up")
(depends-on "smartparens")
(depends-on "smex")
(depends-on "textmate")
(depends-on "yari")
(depends-on "rainbow-mode")
(depends-on "rainbow-delimiters")
(depends-on "elisp-slime-nav")
(depends-on "elixir-mode" :git "https://github.com/elixir-lang/emacs-elixir.git")
(depends-on "alchemist" :git "https://github.com/tonini/alchemist.el.git")