(setq cabbage-bundles '(
                        accessibility
                        completion
                        css
                        cucumber
                        diff
                        ergonomic
                        erlang
                        git
                        html
                        javascript
                        lisp
                        markdown
                        power-edit
                        project
                        python
                        php
                        ruby
                        haml-and-sass
                        yaml
                        cabbage-developer
                        org
                        rails
                        rect-mark
                        snippets
                        github
                        slim
                        mustache
                        dirtree
                        ag
                        rvm
                        tonini-elixir
                        tonini-ido-mode
                        tonini-popwin
                        tonini-karma
                        tonini-popwin
                        tonini-display
                        tonini-bindings
                        coffee-script
                        floobits
                        karma
                        ))
