(setq cabbage-bundles '(
                        accessibility
                        completion
                        css
                        cucumber
                        diff
                        ergonomic
                        erlang
                        git
                        html
                        javascript
                        lisp
                        markdown
                        power-edit
                        project
                        ruby
                        haml-and-sass
                        yaml
                        cabbage-developer
                        org
                        rails
                        snippets
                        github
                        rvm
                        coffee-script
                        tonini-system
                        tonini-elixir
                        tonini-ido-mode
                        tonini-popwin
                        tonini-popwin
                        tonini-display
                        tonini-bindings
                        tonini-js
                        tonini-pbcopy
                        tonini-elisp
                        ))
